travis:
  secure:
    BINSTAR_TOKEN: mhMdt041U9vxHPWEaixufpL4i983yk6FJk9TYw56boEOekP/QvoI0i4Shz0IowoXoAmEe2qpo70+bg9Towuyap9xEeWlPBKfBcdOACKmNxLSEuHXAcOrD4s7ORuh0bjx1m3R2TBmtgH4XlB+pSBoQL5kI8KCRsK5h8yBO/0Aayy2Yr0ykeczpUVihefYo/AbDWxr3EqIQFxddpdPe2AIy1p6qD3q4tuGp/lzlNhl7n/0XDeSWEURTt3dYmURGWmDxsb8OM50VkoTB0YmSKAbkzjAawxlyuX3KbjPUBbv2LN1xL/uMpTEY5m6PHVgoO7dI4CXVkzzUQhYyzboCnZQGtnDvGkzuAUvkbpuWujJG66e//AlpVrg4CtgsPUr7AjpQs0XAjuIWFRsWsJCNXu9ZFykzYL2dw+d7jYq8PGBzb+fNeyWjblLu1B+Et8GTWndQwnN9a36BrTQwJTpEhR5r9CM96Jcg9FeTJ41RQlvCsTSKv0S+bZF33S7UaJ/7LFE7Wwp1Pk9tuxsWr5lxFxD6J/KpU916SnmFEQH+hOGHKK6dZm9QGvZ4rIuxt7P7Iz93yewEij8NExodsWAFAiwr7CaTzlZzPPVtj6iC90I3TiCkFhLgPQB7z+wBle010PP850zygNRwee8vyhaGuNOp4yuHGYwoajp3i4c6PmpICQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
