travis:
  secure:
    BINSTAR_TOKEN: fMfb9CLZrReSJadsV05Zl9rgTRNVHvpum5EkllpblKdBieG4+lUevlIietEohz7Mwxw3RxC/1oit96SVYrKRBXryddAMy0mMXqI9UEYADDOxhZs2gelqWArBHsW4iy3iipNbGpSK6LVR3f3Lg52an9tbYC2Y/kvnuU6JdOlDx+o/QIlUwAMVBSNfWQXIe1t+oivVTe6gJ1tyqtGNrfQO1A5fBcgK/XCKWZ04QWjvNxw36nsBbRh+8ad8v7/vkPEuXCuJ3unlhNbkrtcmpAXAnrmhVf0UeAIjr/sWoLR7OTYPrbZAk/l6j5ThpdWOcgKIob1564bgWzr82N8UnLIA3Ty0KuBcKaGyzDmWWGIrc38AbQXSnqEAs+bLXfR7OlE8WGd1/M2WtzJYRcpEk0BSiCMrzKWu8RNNugk6Oy45c38mTUy9DgHDoiLkj2qdBsI5NSC8CyIgUk7gBGWmi2J50O0juyA92b1GcbLLyJ65MMPR7Hrt5z0FdEPUp2PNKHdm83mnvKzfAruvDmSZ/1AAUaRPspatp6BKbvVjgLa7zLpczO2Wl0zXZuRujqHl7VZXe7ZQDSX5bTJ+g0LoA87gVIeFWbLIWNGt+fKJFgJ8Tb31A+bnq1/DmuDqFYzcXro/OVVoS1KmGxby+rd3DNetQLDzhkcWr+2oT7I6Zlgq/yQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
